version: '3.1'

services:
  jpy:
    image: jupyter/sms_expense_tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    # command: python main.py
    volumes:
      - ./work:/home/jovyan
      - ../data:/data
    environment:
      MONGODB_CONN_STR: ${MONGODB_CONN_STR}